"""The table the engine's ``pyCasefold`` needs, read off this Python's ``str.casefold()``.

``casefold`` is ``lower`` per code point bar the code points listed here; it
has no context rule, so the final sigma never applies.
"""

from __future__ import annotations

import sys
import unicodedata

_SURROGATES = range(0xD800, 0xE000)


def casefold_special() -> dict[int, str]:
    """Every code point whose casefold is not its lowercase."""
    out: dict[int, str] = {}
    for cp in range(sys.maxunicode + 1):
        if cp in _SURROGATES:
            continue
        c = chr(cp)
        if c.casefold() != c.lower():
            out[cp] = c.casefold()
    return out


def render() -> str:
    """The engine's ``src/value/casefold-tables.ts``."""
    numbers = [
        n
        for cp, folded in casefold_special().items()
        for n in [cp, len(folded), *(ord(c) for c in folded)]
    ]
    lines = [
        "\t" + ", ".join(f"0x{n:x}" for n in numbers[i : i + 8]) + ","
        for i in range(0, len(numbers), 8)
    ]
    return (
        "// Generated by tests/golden/casefold_tables.py from Python's str.casefold() "
        f"(Unicode {unicodedata.unidata_version}).\n"
        "// Do not edit: `pixi run golden-fixtures` rewrites it.\n\n"
        "// Code point, the length of its casefold, the casefold; ascending. Only the\n"
        "// code points whose casefold is not their lowercase.\n"
        "export const CASEFOLD_SPECIAL: readonly number[] = [\n"
        + "\n".join(lines)
        + "\n];\n"
    )
