"""The tables the engine's ``pyFloatOf`` needs, read off this Python: every
code point with a decimal digit value, and every code point ``str.isspace()``
accepts (the transform CPython's own float parser applies before the
grammar)."""

from __future__ import annotations

import sys
import unicodedata
from functools import cache

_SURROGATES = range(0xD800, 0xE000)


def _code_points() -> list[int]:
    return [cp for cp in range(sys.maxunicode + 1) if cp not in _SURROGATES]


@cache
def decimal_pairs() -> list[tuple[int, int]]:
    """Every code point with ``unicodedata.decimal`` defined, and its value."""
    out: list[tuple[int, int]] = []
    for cp in _code_points():
        try:
            out.append((cp, unicodedata.decimal(chr(cp))))
        except ValueError:
            pass
    return out


@cache
def space_points() -> list[int]:
    """Every code point ``str.isspace()`` accepts."""
    return [cp for cp in _code_points() if chr(cp).isspace()]


def _array(name: str, numbers: list[int], per_line: int) -> str:
    lines = [
        "\t" + ", ".join(f"0x{n:x}" for n in numbers[i : i + per_line]) + ","
        for i in range(0, len(numbers), per_line)
    ]
    return f"export const {name}: readonly number[] = [\n" + "\n".join(lines) + "\n];\n"


def render() -> str:
    """The engine's ``src/value/digit-tables.ts``."""
    digits = [n for pair in decimal_pairs() for n in pair]
    spaces = space_points()
    header = (
        "// Generated by tests/golden/coerce_tables.py from Python's unicodedata "
        f"(Unicode {unicodedata.unidata_version}).\n"
        "// Do not edit: `pixi run golden-fixtures` rewrites it.\n\n"
        "// Code point, its decimal digit value; ascending.\n"
    )
    return (
        header
        + _array("DECIMAL_DIGITS", digits, 8)
        + "\n// Code points str.isspace() accepts; ascending.\n"
        + _array("SPACE_POINTS", spaces, 8)
    )
