"""The tables the engine's ``pyLower`` needs, read off this Python's ``str.lower()``.

``unicodedata`` exposes neither *cased* nor *case-ignorable*, so both are
derived from the final-sigma rule's behaviour.
"""

from __future__ import annotations

import sys
import unicodedata
from functools import cache

_SURROGATES = range(0xD800, 0xE000)
_FINAL_SIGMA = "ς"


def _code_points() -> list[int]:
    return [cp for cp in range(sys.maxunicode + 1) if cp not in _SURROGATES]


@cache
def _lowered() -> dict[int, str]:
    out: dict[int, str] = {}
    for cp in _code_points():
        lowered = chr(cp).lower()
        if lowered != chr(cp):
            out[cp] = lowered
    return out


def lower_pairs() -> list[tuple[int, int]]:
    return [(cp, ord(s)) for cp, s in _lowered().items() if len(s) == 1]


def lower_special() -> dict[int, list[int]]:
    return {cp: [ord(c) for c in s] for cp, s in _lowered().items() if len(s) > 1}


def _ranges(points: list[int]) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    for cp in points:
        if out and out[-1][1] == cp - 1:
            out[-1] = (out[-1][0], cp)
        else:
            out.append((cp, cp))
    return out


@cache
def _classes() -> tuple[list[tuple[int, int]], list[tuple[int, int]]]:
    cased: list[int] = []
    ignorable: list[int] = []
    for cp in _code_points():
        c = chr(cp)
        if (c + "Σ").lower().endswith(_FINAL_SIGMA):
            cased.append(cp)
        elif ("a" + c + "Σ").lower().endswith(_FINAL_SIGMA):
            ignorable.append(cp)
    return _ranges(cased), _ranges(ignorable)


def cased_ranges() -> list[tuple[int, int]]:
    """Cased and not case-ignorable: decides the final-sigma rule."""
    return _classes()[0]


def case_ignorable_ranges() -> list[tuple[int, int]]:
    """Skipped by the final-sigma rule's scan in both directions."""
    return _classes()[1]


def _array(name: str, numbers: list[int], per_line: int) -> str:
    lines = [
        "\t" + ", ".join(f"0x{n:x}" for n in numbers[i : i + per_line]) + ","
        for i in range(0, len(numbers), per_line)
    ]
    return f"export const {name}: readonly number[] = [\n" + "\n".join(lines) + "\n];\n"


def render() -> str:
    """The engine's ``src/value/lower-tables.ts``."""
    pairs = [n for pair in lower_pairs() for n in pair]
    special = [
        n
        for cp, lowered in lower_special().items()
        for n in [cp, len(lowered), *lowered]
    ]
    cased = [n for r in cased_ranges() for n in r]
    ignorable = [n for r in case_ignorable_ranges() for n in r]
    header = (
        "// Generated by tests/golden/lower_tables.py from Python's str.lower() "
        f"(Unicode {unicodedata.unidata_version}).\n"
        "// Do not edit: `pixi run golden-fixtures` rewrites it.\n\n"
        "// Code point, its lowercase; ascending.\n"
    )
    return (
        header
        + _array("LOWER_PAIRS", pairs, 8)
        + "\n// Code point, the length of its lowercase, the lowercase.\n"
        + _array("LOWER_SPECIAL", special, 8)
        + "\n// Inclusive ranges, ascending: cased and not case-ignorable.\n"
        + _array("CASED_RANGES", cased, 8)
        + "\n// Inclusive ranges, ascending: case-ignorable.\n"
        + _array("CASE_IGNORABLE_RANGES", ignorable, 8)
    )
