"""The tables the engine's regex translator needs, read off this Python's ``re``:
the code points ``\\w``, ``\\d`` and ``\\s`` accept on a ``str``, and the case
data ``re`` matches ``IGNORECASE`` with (``_sre``'s simple lowercase, its
*cased* test and the compiler's extra equivalences)."""

from __future__ import annotations

import importlib
import re
import sys
import unicodedata
from functools import cache
from re._casefix import _EXTRA_CASES

# The matcher's own case functions; the module ships no type stubs.
_sre = importlib.import_module("_sre")

_SURROGATES = range(0xD800, 0xE000)


def _code_points() -> list[int]:
    return [cp for cp in range(sys.maxunicode + 1) if cp not in _SURROGATES]


def _ranges(points: list[int]) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    for cp in points:
        if out and out[-1][1] == cp - 1:
            out[-1] = (out[-1][0], cp)
        else:
            out.append((cp, cp))
    return out


@cache
def _accepted(pattern: str) -> tuple[int, ...]:
    compiled = re.compile(pattern)
    return tuple(cp for cp in _code_points() if compiled.fullmatch(chr(cp)))


def word_ranges() -> list[tuple[int, int]]:
    return _ranges(list(_accepted(r"\w")))


def digit_ranges() -> list[tuple[int, int]]:
    return _ranges(list(_accepted(r"\d")))


def space_ranges() -> list[tuple[int, int]]:
    return _ranges(list(_accepted(r"\s")))


@cache
def ignorecase_lower() -> dict[int, int]:
    """Every code point whose ``IGNORECASE`` lowercase differs from it, and that
    lowercase (one code point, unlike ``str.lower()``: ``İ`` gives ``i``)."""
    out: dict[int, int] = {}
    for cp in _code_points():
        lowered = _sre.unicode_tolower(cp)
        if lowered != cp:
            out[cp] = lowered
    return out


def ignorecase_cased_ranges() -> list[tuple[int, int]]:
    return _ranges([cp for cp in _code_points() if _sre.unicode_iscased(cp)])


def ignorecase_extra() -> dict[int, tuple[int, ...]]:
    """Lowercases ``IGNORECASE`` treats as equal although no lowercase joins them."""
    return dict(sorted(_EXTRA_CASES.items()))


def _check_branch_merge() -> None:
    # `re` folds `a|\W`-style branches into one set matched on the lowercase;
    # the engine keeps them apart, which agrees only while no lowercase leaves
    # a class and every lowercase target is itself cased.
    word, digit, space = (set(_accepted(p)) for p in (r"\w", r"\d", r"\s"))
    for cp, lowered in ignorecase_lower().items():
        for accepted in (word, digit, space):
            if (cp in accepted) != (lowered in accepted):
                raise AssertionError(f"U+{cp:04X} and its lowercase differ in a class")
        if not _sre.unicode_iscased(lowered):
            raise AssertionError(f"U+{lowered:04X} is a lowercase target but not cased")


def _array(name: str, numbers: list[int], per_line: int) -> str:
    lines = [
        "\t" + ", ".join(f"0x{n:x}" for n in numbers[i : i + per_line]) + ","
        for i in range(0, len(numbers), per_line)
    ]
    return f"export const {name}: readonly number[] = [\n" + "\n".join(lines) + "\n];\n"


def _flat(ranges: list[tuple[int, int]]) -> list[int]:
    return [n for r in ranges for n in r]


def render() -> str:
    """The engine's ``src/value/regex-tables.ts``."""
    _check_branch_merge()
    lower = [n for pair in ignorecase_lower().items() for n in pair]
    extra = [n for k, vs in ignorecase_extra().items() for n in [k, len(vs), *vs]]
    header = (
        "// Generated by tests/golden/regex_tables.py from Python's re "
        f"(Unicode {unicodedata.unidata_version}).\n"
        "// Do not edit: `pixi run golden-fixtures` rewrites it.\n\n"
        "// Inclusive ranges, ascending: what \\w accepts on a str.\n"
    )
    return (
        header
        + _array("WORD_RANGES", _flat(word_ranges()), 8)
        + "\n// Inclusive ranges, ascending: what \\d accepts on a str.\n"
        + _array("DIGIT_RANGES", _flat(digit_ranges()), 8)
        + "\n// Inclusive ranges, ascending: what \\s accepts on a str.\n"
        + _array("SPACE_RANGES", _flat(space_ranges()), 8)
        + "\n// Code point, its IGNORECASE lowercase; ascending.\n"
        + _array("IGNORECASE_LOWER", lower, 8)
        + "\n// Inclusive ranges, ascending: cased under IGNORECASE.\n"
        + _array("IGNORECASE_CASED_RANGES", _flat(ignorecase_cased_ranges()), 8)
        + "\n// Lowercase, the number of its extra equivalents, the equivalents.\n"
        + _array("IGNORECASE_EXTRA", extra, 8)
    )
