"""The script facade's source, embedded for the engine's guest."""

from __future__ import annotations

import json

from data_rover.core.script.facade_src import FACADE_SOURCE


def render() -> str:
    """The engine's ``src/script/facade.generated.ts``."""
    return (
        "// Generated by tests/golden/script_facade.py from "
        "data_rover.core.script.facade_src.FACADE_SOURCE.\n"
        "// Do not edit: `pixi run golden-fixtures` rewrites it.\n\n"
        "// The Python source the guest executes before a script.\n"
        f"export const FACADE_SOURCE: string = {json.dumps(FACADE_SOURCE)};\n"
    )
