"""The script harness's source, embedded for the engine's guest."""

from __future__ import annotations

import json

from data_rover.core.script.harness_src import HARNESS_SOURCE


def render() -> str:
    """The engine's ``src/script/harness.generated.ts``."""
    return (
        "// Generated by tests/golden/script_harness.py from "
        "data_rover.core.script.harness_src.HARNESS_SOURCE.\n"
        "// Do not edit: `pixi run golden-fixtures` rewrites it.\n\n"
        "// The Python source the guest executes to run a script or an embedded call.\n"
        f"export const HARNESS_SOURCE: string = {json.dumps(HARNESS_SOURCE)};\n"
    )
