"""The character widths the engine's xlsx autofit needs, read off xlsxwriter."""

from __future__ import annotations

import xlsxwriter  # type: ignore[import-untyped]
from xlsxwriter.utility import CHAR_WIDTHS, xl_pixel_width  # type: ignore[import-untyped]

#: a character outside ``CHAR_WIDTHS``
_UNLISTED = "Ā"


def render() -> str:
    """The engine's ``src/export/xlsx-widths.ts``."""
    assert _UNLISTED not in CHAR_WIDTHS
    entries = sorted((ord(char), width) for char, width in CHAR_WIDTHS.items())
    lines = [f"\t[0x{cp:x}, {width}]," for cp, width in entries]
    return (
        "// Generated by tests/golden/xlsx_widths.py from xlsxwriter "
        f"{xlsxwriter.__version__}'s CHAR_WIDTHS.\n"
        "// Do not edit: `pixi run golden-fixtures` rewrites it.\n\n"
        "// Pixels per code point in xlsxwriter's autofit; any other code point is\n"
        "// DEFAULT_CHAR_WIDTH.\n"
        "export const CHAR_WIDTHS: ReadonlyMap<number, number> = new Map([\n"
        + "\n".join(lines)
        + "\n]);\n\n"
        f"export const DEFAULT_CHAR_WIDTH = {xl_pixel_width(_UNLISTED)};\n"
    )
