"""What the engine's xlsx writer takes from xlsxwriter: the theme part it
writes, and what quoting a sheet name as ``quote_sheetname`` does needs, read
off xlsxwriter's patterns and this Python's ``str.upper()``."""

from __future__ import annotations

import json
import re
import unicodedata
from io import StringIO

import xlsxwriter  # type: ignore[import-untyped]
from xlsxwriter.theme import Theme  # type: ignore[import-untyped]
from xlsxwriter.utility import (  # type: ignore[import-untyped]
    RE_QUOTE_RULE1,
    RE_QUOTE_RULE2,
)

from .regex_tables import _code_points, _ranges

#: what ``quote_sheetname``'s rules 3 and 4 match on the upper-cased name
_REFERENCE_CHAR = re.compile(r"[A-Z\d]")


def _rows(ranges: list[tuple[int, int]]) -> str:
    flat = [f"0x{cp:x}" for pair in ranges for cp in pair]
    return "\n".join(
        "\t" + ", ".join(flat[i : i + 8]) + "," for i in range(0, len(flat), 8)
    )


def _ts_string(text: str) -> str:
    return "'" + "".join(f"\\u{ord(c):04x}" for c in text) + "'"


def _theme() -> str:
    buffer = StringIO()
    theme = Theme()
    theme._set_xml_writer(buffer)
    theme._assemble_xml_file()
    return buffer.getvalue()


def render() -> str:
    """The engine's ``src/export/xlsx-tables.ts``."""
    plain = [cp for cp in _code_points() if not RE_QUOTE_RULE1.search(chr(cp))]
    quoted_start = [cp for cp in _code_points() if RE_QUOTE_RULE2.search(chr(cp))]
    upper = [
        (cp, chr(cp).upper())
        for cp in _code_points()
        if cp > 0x7F
        and chr(cp).upper() != chr(cp)
        and _REFERENCE_CHAR.search(chr(cp).upper())
    ]
    pairs = "\n".join(f"\t[0x{cp:x}, {_ts_string(text)}]," for cp, text in upper)
    return (
        "// Generated by tests/golden/xlsx_tables.py from xlsxwriter "
        f"{xlsxwriter.__version__}'s theme and quote_sheetname, and Python's str.upper()"
        f" (Unicode {unicodedata.unidata_version}).\n"
        "// Do not edit: `pixi run golden-fixtures` rewrites it.\n\n"
        "// Inclusive ranges, ascending: what a sheet name may hold unquoted\n"
        "// (\\w, '.' and xlsxwriter's emoji).\n"
        "export const PLAIN_NAME_RANGES: readonly number[] = [\n"
        + _rows(_ranges(plain))
        + "\n];\n\n"
        "// Inclusive ranges, ascending: what a sheet name may not start with\n"
        "// unquoted (\\d, '.' and xlsxwriter's emoji).\n"
        "export const QUOTED_START_RANGES: readonly number[] = [\n"
        + _rows(_ranges(quoted_start))
        + "\n];\n\n"
        "// Code point, its str.upper(): every one past ASCII that upper-cases to\n"
        "// something else holding an ASCII capital or a digit.\n"
        "export const UPPER_REFERENCE: ReadonlyMap<number, string> = new Map([\n"
        + pairs
        + "\n]);\n\n"
        "// xl/theme/theme1.xml, as xlsxwriter writes it.\n"
        f"export const THEME_XML = {json.dumps(_theme())};\n"
    )
