"""Writes, or with ``--check`` verifies, the engine source files derived from
this Python's standard library, xlsxwriter and the script facade.

The casefold, lower, digit and regex tables are read off ``str``, ``unicodedata``
and ``re``; ``facade.generated.ts`` embeds ``FACADE_SOURCE``; ``xlsx-widths.ts``
and ``xlsx-tables.ts`` come from xlsxwriter. ``--check`` prints each file that is
missing or differs and exits 1.
"""

from __future__ import annotations

import argparse
import importlib
import json
import re
import sys
import unicodedata
from collections.abc import Callable
from functools import cache
from io import StringIO
from pathlib import Path
from re._casefix import _EXTRA_CASES

import xlsxwriter  # type: ignore[import-untyped]
from xlsxwriter.theme import Theme  # type: ignore[import-untyped]
from xlsxwriter.utility import (  # type: ignore[import-untyped]
    CHAR_WIDTHS,
    RE_QUOTE_RULE1,
    RE_QUOTE_RULE2,
    xl_pixel_width,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from data_rover.core.script.facade_src import FACADE_SOURCE  # noqa: E402

# The matcher's own case functions; the module ships no type stubs.
_sre = importlib.import_module("_sre")

_SURROGATES = range(0xD800, 0xE000)
_FINAL_SIGMA = "ς"
#: a character outside ``CHAR_WIDTHS``
_UNLISTED = "Ā"
#: what ``quote_sheetname``'s rules 3 and 4 match on the upper-cased name
_REFERENCE_CHAR = re.compile(r"[A-Z\d]")

_NOTICE = "// Do not edit: `pixi run -e core-dev python scripts/engine_tables.py` rewrites it.\n\n"


def _code_points() -> list[int]:
    return [cp for cp in range(sys.maxunicode + 1) if cp not in _SURROGATES]


def _ranges(points: list[int]) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    for cp in points:
        if out and out[-1][1] == cp - 1:
            out[-1] = (out[-1][0], cp)
        else:
            out.append((cp, cp))
    return out


def _flat(ranges: list[tuple[int, int]]) -> list[int]:
    return [n for r in ranges for n in r]


def _array(name: str, numbers: list[int], per_line: int) -> str:
    lines = [
        "\t" + ", ".join(f"0x{n:x}" for n in numbers[i : i + per_line]) + ","
        for i in range(0, len(numbers), per_line)
    ]
    return f"export const {name}: readonly number[] = [\n" + "\n".join(lines) + "\n];\n"


def _rows(ranges: list[tuple[int, int]]) -> str:
    flat = [f"0x{cp:x}" for pair in ranges for cp in pair]
    return "\n".join(
        "\t" + ", ".join(flat[i : i + 8]) + "," for i in range(0, len(flat), 8)
    )


def _ts_string(text: str) -> str:
    return "'" + "".join(f"\\u{ord(c):04x}" for c in text) + "'"


# casefold-tables.ts: ``casefold`` is ``lower`` per code point bar the code
# points listed, and has no context rule, so the final sigma never applies.


def render_casefold() -> str:
    special: dict[int, str] = {}
    for cp in _code_points():
        c = chr(cp)
        if c.casefold() != c.lower():
            special[cp] = c.casefold()
    numbers = [
        n
        for cp, folded in special.items()
        for n in [cp, len(folded), *(ord(c) for c in folded)]
    ]
    lines = [
        "\t" + ", ".join(f"0x{n:x}" for n in numbers[i : i + 8]) + ","
        for i in range(0, len(numbers), 8)
    ]
    return (
        "// Generated by scripts/engine_tables.py from Python's str.casefold() "
        f"(Unicode {unicodedata.unidata_version}).\n"
        + _NOTICE
        + "// Code point, the length of its casefold, the casefold; ascending. Only the\n"
        "// code points whose casefold is not their lowercase.\n"
        "export const CASEFOLD_SPECIAL: readonly number[] = [\n"
        + "\n".join(lines)
        + "\n];\n"
    )


# lower-tables.ts: ``unicodedata`` exposes neither *cased* nor *case-ignorable*,
# so both are derived from the final-sigma rule's behaviour.


@cache
def _lowered() -> dict[int, str]:
    out: dict[int, str] = {}
    for cp in _code_points():
        lowered = chr(cp).lower()
        if lowered != chr(cp):
            out[cp] = lowered
    return out


@cache
def _sigma_classes() -> tuple[list[tuple[int, int]], list[tuple[int, int]]]:
    cased: list[int] = []
    ignorable: list[int] = []
    for cp in _code_points():
        c = chr(cp)
        if (c + "Σ").lower().endswith(_FINAL_SIGMA):
            cased.append(cp)
        elif ("a" + c + "Σ").lower().endswith(_FINAL_SIGMA):
            ignorable.append(cp)
    return _ranges(cased), _ranges(ignorable)


def render_lower() -> str:
    pairs = [n for cp, s in _lowered().items() if len(s) == 1 for n in (cp, ord(s))]
    special = [
        n
        for cp, s in _lowered().items()
        if len(s) > 1
        for n in [cp, len(s), *(ord(c) for c in s)]
    ]
    cased, ignorable = _sigma_classes()
    header = (
        "// Generated by scripts/engine_tables.py from Python's str.lower() "
        f"(Unicode {unicodedata.unidata_version}).\n"
        + _NOTICE
        + "// Code point, its lowercase; ascending.\n"
    )
    return (
        header
        + _array("LOWER_PAIRS", pairs, 8)
        + "\n// Code point, the length of its lowercase, the lowercase.\n"
        + _array("LOWER_SPECIAL", special, 8)
        + "\n// Inclusive ranges, ascending: cased and not case-ignorable.\n"
        + _array("CASED_RANGES", _flat(cased), 8)
        + "\n// Inclusive ranges, ascending: case-ignorable.\n"
        + _array("CASE_IGNORABLE_RANGES", _flat(ignorable), 8)
    )


# digit-tables.ts: every code point with a decimal digit value, and every code
# point ``str.isspace()`` accepts (the transform CPython's own float parser
# applies before the grammar).


def render_digits() -> str:
    digits: list[int] = []
    for cp in _code_points():
        try:
            digits += [cp, unicodedata.decimal(chr(cp))]
        except ValueError:
            pass
    spaces = [cp for cp in _code_points() if chr(cp).isspace()]
    header = (
        "// Generated by scripts/engine_tables.py from Python's unicodedata "
        f"(Unicode {unicodedata.unidata_version}).\n"
        + _NOTICE
        + "// Code point, its decimal digit value; ascending.\n"
    )
    return (
        header
        + _array("DECIMAL_DIGITS", digits, 8)
        + "\n// Code points str.isspace() accepts; ascending.\n"
        + _array("SPACE_POINTS", spaces, 8)
    )


# regex-tables.ts: the code points ``\w``, ``\d`` and ``\s`` accept on a
# ``str``, and the case data ``re`` matches ``IGNORECASE`` with (``_sre``'s
# simple lowercase, its *cased* test and the compiler's extra equivalences).


@cache
def _accepted(pattern: str) -> tuple[int, ...]:
    compiled = re.compile(pattern)
    return tuple(cp for cp in _code_points() if compiled.fullmatch(chr(cp)))


@cache
def _ignorecase_lower() -> dict[int, int]:
    """Every code point whose ``IGNORECASE`` lowercase differs from it, and that
    lowercase (one code point, unlike ``str.lower()``: ``İ`` gives ``i``)."""
    out: dict[int, int] = {}
    for cp in _code_points():
        lowered = _sre.unicode_tolower(cp)
        if lowered != cp:
            out[cp] = lowered
    return out


def _check_branch_merge() -> None:
    # `re` folds `a|\W`-style branches into one set matched on the lowercase;
    # the engine keeps them apart, which agrees only while no lowercase leaves
    # a class and every lowercase target is itself cased.
    word, digit, space = (set(_accepted(p)) for p in (r"\w", r"\d", r"\s"))
    for cp, lowered in _ignorecase_lower().items():
        for accepted in (word, digit, space):
            if (cp in accepted) != (lowered in accepted):
                raise AssertionError(f"U+{cp:04X} and its lowercase differ in a class")
        if not _sre.unicode_iscased(lowered):
            raise AssertionError(f"U+{lowered:04X} is a lowercase target but not cased")


def render_regex() -> str:
    _check_branch_merge()
    lower = [n for pair in _ignorecase_lower().items() for n in pair]
    cased = _ranges([cp for cp in _code_points() if _sre.unicode_iscased(cp)])
    extra = [n for k, vs in sorted(_EXTRA_CASES.items()) for n in [k, len(vs), *vs]]
    header = (
        "// Generated by scripts/engine_tables.py from Python's re "
        f"(Unicode {unicodedata.unidata_version}).\n"
        + _NOTICE
        + "// Inclusive ranges, ascending: what \\w accepts on a str.\n"
    )
    return (
        header
        + _array("WORD_RANGES", _flat(_ranges(list(_accepted(r"\w")))), 8)
        + "\n// Inclusive ranges, ascending: what \\d accepts on a str.\n"
        + _array("DIGIT_RANGES", _flat(_ranges(list(_accepted(r"\d")))), 8)
        + "\n// Inclusive ranges, ascending: what \\s accepts on a str.\n"
        + _array("SPACE_RANGES", _flat(_ranges(list(_accepted(r"\s")))), 8)
        + "\n// Code point, its IGNORECASE lowercase; ascending.\n"
        + _array("IGNORECASE_LOWER", lower, 8)
        + "\n// Inclusive ranges, ascending: cased under IGNORECASE.\n"
        + _array("IGNORECASE_CASED_RANGES", _flat(cased), 8)
        + "\n// Lowercase, the number of its extra equivalents, the equivalents.\n"
        + _array("IGNORECASE_EXTRA", extra, 8)
    )


# facade.generated.ts: the Python source the guest executes before a script.


def render_facade() -> str:
    return (
        "// Generated by scripts/engine_tables.py from "
        "data_rover.core.script.facade_src.FACADE_SOURCE.\n"
        + _NOTICE
        + "// The Python source the guest executes before a script.\n"
        f"export const FACADE_SOURCE: string = {json.dumps(FACADE_SOURCE)};\n"
    )


# xlsx-widths.ts: the character widths the engine's xlsx autofit needs.


def render_xlsx_widths() -> str:
    assert _UNLISTED not in CHAR_WIDTHS
    entries = sorted((ord(char), width) for char, width in CHAR_WIDTHS.items())
    lines = [f"\t[0x{cp:x}, {width}]," for cp, width in entries]
    return (
        "// Generated by scripts/engine_tables.py from xlsxwriter "
        f"{xlsxwriter.__version__}'s CHAR_WIDTHS.\n"
        + _NOTICE
        + "// Pixels per code point in xlsxwriter's autofit; any other code point is\n"
        "// DEFAULT_CHAR_WIDTH.\n"
        "export const CHAR_WIDTHS: ReadonlyMap<number, number> = new Map([\n"
        + "\n".join(lines)
        + "\n]);\n\n"
        f"export const DEFAULT_CHAR_WIDTH = {xl_pixel_width(_UNLISTED)};\n"
    )


# xlsx-tables.ts: the theme part the engine's writer emits, and what quoting a
# sheet name as ``quote_sheetname`` does needs, read off xlsxwriter's patterns
# and this Python's ``str.upper()``.


def _theme() -> str:
    buffer = StringIO()
    theme = Theme()
    theme._set_xml_writer(buffer)
    theme._assemble_xml_file()
    return buffer.getvalue()


def render_xlsx_tables() -> str:
    plain = [cp for cp in _code_points() if not RE_QUOTE_RULE1.search(chr(cp))]
    quoted_start = [cp for cp in _code_points() if RE_QUOTE_RULE2.search(chr(cp))]
    upper = [
        (cp, chr(cp).upper())
        for cp in _code_points()
        if cp > 0x7F
        and chr(cp).upper() != chr(cp)
        and _REFERENCE_CHAR.search(chr(cp).upper())
    ]
    pairs = "\n".join(f"\t[0x{cp:x}, {_ts_string(text)}]," for cp, text in upper)
    return (
        "// Generated by scripts/engine_tables.py from xlsxwriter "
        f"{xlsxwriter.__version__}'s theme and quote_sheetname, and Python's str.upper()"
        f" (Unicode {unicodedata.unidata_version}).\n"
        + _NOTICE
        + "// Inclusive ranges, ascending: what a sheet name may hold unquoted\n"
        "// (\\w, '.' and xlsxwriter's emoji).\n"
        "export const PLAIN_NAME_RANGES: readonly number[] = [\n"
        + _rows(_ranges(plain))
        + "\n];\n\n"
        "// Inclusive ranges, ascending: what a sheet name may not start with\n"
        "// unquoted (\\d, '.' and xlsxwriter's emoji).\n"
        "export const QUOTED_START_RANGES: readonly number[] = [\n"
        + _rows(_ranges(quoted_start))
        + "\n];\n\n"
        "// Code point, its str.upper(): every one past ASCII that upper-cases to\n"
        "// something else holding an ASCII capital or a digit.\n"
        "export const UPPER_REFERENCE: ReadonlyMap<number, string> = new Map([\n"
        + pairs
        + "\n]);\n\n"
        "// xl/theme/theme1.xml, as xlsxwriter writes it.\n"
        f"export const THEME_XML = {json.dumps(_theme())};\n"
    )


GENERATED: dict[Path, Callable[[], str]] = {
    Path("engine/src/value/casefold-tables.ts"): render_casefold,
    Path("engine/src/value/lower-tables.ts"): render_lower,
    Path("engine/src/value/digit-tables.ts"): render_digits,
    Path("engine/src/value/regex-tables.ts"): render_regex,
    Path("engine/src/script/facade.generated.ts"): render_facade,
    Path("engine/src/export/xlsx-widths.ts"): render_xlsx_widths,
    Path("engine/src/export/xlsx-tables.ts"): render_xlsx_tables,
}


def stale() -> list[str]:
    """The generated files that are missing or differ, by path from the
    repository."""
    return [
        rel.as_posix()
        for rel, make in GENERATED.items()
        if not (REPO_ROOT / rel).is_file()
        or (REPO_ROOT / rel).read_text(encoding="utf-8") != make()
    ]


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").split("\n\n")[0])
    parser.add_argument(
        "--check", action="store_true", help="report stale files and write nothing"
    )
    args = parser.parse_args(argv)
    if args.check:
        names = stale()
        for name in names:
            print(f"stale: {name}")
        return 1 if names else 0
    for rel, make in GENERATED.items():
        (REPO_ROOT / rel).write_text(make(), encoding="utf-8")
        print(f"wrote {rel.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
